### ISSUE TITLE
BORA mainnet 앤드포인트 교체 요청

### ISSUE THREAD

**Issue by PrrrStar** [HAECHI-LABS/face-sample-dapp#23]
BORA Mainnet 은 Public Endpoint 를 사용할 수 있는데,
`https://public-node.api.boraportal.io/bora/mainnet` 이 주소로 교체 요청드립니다.

https://github.com/HAECHI-LABS/face-sample-dapp/blob/361a94db4a02fbf34eb503d711b7b2d50838e87a/src/lib/utils.js#L57C21-L57C21

**Comment by ellemedit** [comment]
close by https://github.com/HAECHI-LABS/face-sample-dapp/pull/25#issue-2019997401
